### PR TITLE
79/fix missing operators invalid sql missing visitors

### LINKED ISSUE #33: Handle multiple tree entries in pg_query_visitor#accept
When executing multiple statements in a single SQL string the `PgQueryVisitor` throws an error for example:

```
SELECT 1; -- statement 1
SELECT 2; -- statement 2
```

Let's extend the public API of sql_to_arel to handle single and multiple returns

### LINKED ISSUE #79: Fix invalid generated SQL, add missing visitors and extend operators
I've installed `arel_toolkit` into a production system using an around hook in the ApplicationController with some dummy middleware. After running the test suite it became clear that a lot of operators, branches, visitors, compatibility with existing gems and other things are still missing.

At least:
- JSON(b) operators
- EXTRACT FROM
- AT TIME ZONE
- Compatibility with [active_record_upsert](https://github.com/jesjos/active_record_upsert)
- Handling of multiple SQL statements #33 
- ActiveRecord Bind values for UPDATE and INSERT
- We need to have Arel for transactions
- missing visit_VariableSetStmt
- enhanced error reporting to make debugging easier
- properly handle quoted values

### PR DESCRIPTION
**Pull request by mvgijssel**
fixes #79 
fixes #33

### CODE REVIEW

File: spec/arel/sql_to_arel_spec.rb [hunk 1]
```diff
@@ -406,7 +420,17 @@ def ast_contains_constant(tree, constant)
           '3 || ARRAY[4, 5, 6], ' \
           'ARRAY[4, 5, 6] || 7, ' \
           "'192.168.1/24'::inet <<= '192.168.1/24'::inet, " \
-          "'192.168.1/24'::inet >>= '192.168.1/24::inet'"
```
Comment (mvgijssel) [inline spec/arel/sql_to_arel_spec.rb:409]: Revert this

File: lib/arel/extensions/insert_statement.rb [hunk 2]
```diff
@@ -6,7 +6,7 @@ module Nodes
     # https://www.postgresql.org/docs/9.5/sql-insert.html
     Arel::Nodes::InsertStatement.class_eval do
       attr_accessor :with
-      attr_accessor :on_conflict
```
Comment (mvgijssel) [inline lib/arel/extensions/insert_statement.rb:9]: File an issue to better test compatibility with other Arel extending libraries.

File: lib/arel/extensions/json_get_field.rb [hunk 3]
```diff
@@ -0,0 +1,21 @@
+# rubocop:disable Naming/MethodName
+# rubocop:disable Naming/UncommunicativeMethodParamName
+
+module Arel
+  module Nodes
+    # https://www.postgresql.org/docs/9.3/functions-net.html
```
Comment (mvgijssel) [inline lib/arel/extensions/json_get_field.rb]: Check the links for all the extensions

File: lib/arel/sql_to_arel/pg_query_visitor.rb [hunk 4]
```diff
@@ -10,6 +10,16 @@
 
 module Arel
   module SqlToArel
+    class Result < Array
```
Comment (mvgijssel) [inline lib/arel/sql_to_arel/pg_query_visitor.rb]: Move to a separate file

File: lib/arel/sql_to_arel/pg_query_visitor.rb [hunk 5]
```diff
@@ -20,12 +30,15 @@ class PgQueryVisitor
...
-        boom 'https://github.com/mvgijssel/arel_toolkit/issues/33' if tree.length > 1
 
-        @object = tree.first
+        @object = tree
         @binds = binds
         @sql = sql
-        visit object, :top
+        result = Result.new
+
+        visit(object, :top).each { |arel| result << arel }
```
Comment (mvgijssel) [inline lib/arel/sql_to_arel/pg_query_visitor.rb]: Just Result.new visit, not so complicated

File: lib/arel/extensions/insert_statement.rb (hunk 2 above)
Comment (mvgijssel) [reply lib/arel/extensions/insert_statement.rb:9]: https://github.com/mvgijssel/arel_toolkit/issues/81
