### PR TITLE
Fix visit_ParamRef argument

### LINKED ISSUE #69: NameError: undefined local variable or method `number' for #<Arel::SqlToArel::PgQueryVisitor:0x000055dfdd14c6f8>
When binds are present in the visitor, `number` is undefined:

```
      def visit_ParamRef(_args)
        value = (binds[number - 1] unless binds.empty?)

        Arel::Nodes::BindParam.new(value)
      end
```

### PR DESCRIPTION
**Pull request by mvgijssel**
fixes #69

### CODE REVIEW

File: spec/arel/middleware_spec.rb [hunk 1]
```diff
@@ -207,10 +207,12 @@ def self.call(arel)
     expect_any_instance_of(ActiveRecord::ConnectionAdapters::PostgreSQLAdapter)
       .to receive(:exec_no_cache_without_arel_middleware).twice.and_call_original
 
-    Post.where(id: [1, 2]).load # IN statements are not prepared
+    Arel.middleware.apply([SomeMiddleware]) do
```
Comment (mvgijssel) [inline spec/arel/middleware_spec.rb:210]: Adding the middleware block here also triggers the error
